# -*- coding: utf-8 -*-


{
    'name': 'Hammam customizations',
    'version': '15.0.1.0',
 #   'category': 'Studio',
      'category': 'Uncategorized',
      'description': u""",
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.

""",
   "author": "Hammams Co",
     "website": "https://Hammam.com",
  #  "license": "OPL-1",
    'depends': [
        'base',
        'contacts',
        'mail',
        'sms',
        'web_studio',
    ],
    'data': [
        'view/transport_type_view.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        
    ],
    'application': False,
    "auto_install": False,
    "installable": True,
  #          "web.assets_common": [
   #         "hammam_customizations/static/**/*",
    #    ],
}
